# Generated by Django 4.2.1 on 2023-05-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_pacientes_cuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='peso',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='talla',
            field=models.FloatField(null=True),
        ),
    ]
