# Generated by Django 4.2.1 on 2023-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agenda_descripcion_alter_ficha_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
    ]
