# Generated by Django 4.2.1 on 2023-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_agenda_id_remove_ficha_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='paciente',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='paciente',
            field=models.CharField(max_length=11),
        ),
    ]
