# Generated by Django 4.2.1 on 2023-05-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_delete_recetario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recetas',
        ),
    ]
